name: Deploy or Destroy Medusa

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: | 
          terraform apply -auto-approve tfplan
          echo "EC2_HOST=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
          echo ${{ env.EC2_HOST }}
        working-directory: ./terraform

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Update and Install Dependencies
        if: github.event.inputs.action == 'apply'
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 ubuntu@${{ env.EC2_HOST }} << 'EOF'
            # Update system packages
            sudo apt-get update -y
            sudo apt-get upgrade -y

            # Install Docker, Node.js, PostgreSQL, Redis, AWS CLI
            sudo apt-get install -y docker.io awscli postgresql postgresql-contrib redis-server
            sudo apt-get install -y curl
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt install -y nodejs

            # Enable and start PostgreSQL and Redis
            sudo systemctl start postgresql
            sudo systemctl enable postgresql
            sudo systemctl start redis-server
            sudo systemctl enable redis-server

            # Create PostgreSQL database and user
            sudo -u postgres psql -c "CREATE USER medusabackend WITH PASSWORD 'medusa123' CREATEDB;"
            sudo -u postgres psql -c "CREATE DATABASE medusabackend OWNER medusabackend;"
            sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE medusabackend TO medusabackend;"

            # Clone the Medusa app repository
            if [ -d "./my-app-store" ]; then
              sudo rm -rf ./my-app-store
            fi
            git clone https://github.com/palemanudeep/TASK-1.git ./my-app-store
            cd ./my-app-store

            # Set up .env file for Medusa
            echo "DATABASE_URL=postgres://medusabackend:medusa123@localhost:5432/medusabackend" > .env
            echo "REDIS_URL=redis://localhost:6379" >> .env

            # Install Medusa dependencies
            sudo npm install -g @medusajs/medusa-cli
            npm install
            npm install cross-env --save-dev

            # Run database migrations
            npx medusa migrations run

            # Create Medusa admin user
            npx medusa user -e anudeep@gmail.com -p anudeep123
            
            # Kill any process running on port 9000
            if lsof -i :9000; then
              lsof -ti:9000 | xargs kill -9
            fi

            # Start Medusa application in the background
            nohup sudo npm run start &> medusa.log &

            echo "Medusa deployment initiated."

            # Create Dockerfile for Medusa
            cat << 'EOF2' > Dockerfile
            FROM node:hydrogen-alpine3.20
            WORKDIR /app
            COPY package.json ./ 
            RUN npm install && npm install -g @medusajs/medusa-cli@latest
            RUN npm install --legacy-peer-deps || npm install --force
            COPY . .
            EXPOSE 7001 9000
            CMD ["medusa", "start"]
          EOF2

            sudo docker build -t medusa/medusa-app:latest .

            # Install AWS CLI
            sudo apt-get install -y awscli

            # Authenticate Docker to AWS ECR
            aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 440744245577.dkr.ecr.ap-south-1.amazonaws.com

            # Tag the Docker image
            sudo docker tag medusa/medusa-app:latest 440744245577.dkr.ecr.ap-south-1.amazonaws.com/medusa/medusa-app:latest

            # Push the Docker image to ECR
            sudo docker push 440744245577.dkr.ecr.ap-south-1.amazonaws.com/medusa/medusa-app:latest

            echo "Medusa Docker image built and pushed to ECR."
          EOF
